### ISSUE TITLE
Election results not sent in catchup 

### ISSUE THREAD

**Issue by Tesa27** [dedis/popstellar#1027]
- idea is to store election result on election channels when broadcast by go server
    - this is problematic since it is defined that the server is not supposed to create 
       messages, so election results should only be broadcast but not sorted by the backend. This causes 
       problems if someone joins an election too late, the catchup will not include the registered votes.
       An idea would be to recomputed the election results on every catchup but this can cause an overhead in 
       terms of computation and even network traffic.
    - Temporary solution is to store results on lection channel even if backend is not supposed to create messages and 
       is supposed to be more passive and creating messages is active.

**Comment by Robingoumaz** [comment]
Also with the implementation of the new features in e-voting lao#greet and election#key messages, the backend sends messages.
