### ISSUE TITLE
[FE2] Digital Cash - Missing check end semester summer/2022

### ISSUE THREAD

**Issue by zoemarin** [dedis/popstellar#1168]
### Description (Actual behavior)
You can send money via the digital cash feature but the signature and the max amount you can send are not check

### Expected behavior
signature of the transaction and the max amount you can send should be check

### Version & Environment
This bug was reproduced on:
- Commit: ef9c0c655804133a3354e02df8ae02856b845b25

##### Front-ends:
- [ ] Fe1-Web (please include browser's names & version)
- [ X] Fe2-Android (please specify if phone or emulation, and Android version)
- [ ] Not applicable

##### Back-ends:
- [ ] Be1-Go
- [ ] Be2-Scala
- [X ] Not applicable

### Impact
could lead to unexpected behavior

**Comment by lourkeur** [comment]
Fixed by #1167
