### ISSUE TITLE
[BUG] The count of people in the roll call may become wrong

### ISSUE THREAD

**Issue by Warhedgehog** [dedis/popstellar#1227]
### Description (Actual behavior)
The count of scanned people in a roll call may become wrong

### Expected behavior
We expect the count to reflect the number of QR code scanned and that already scanned QR code are not counted multiple times.

### How to reproduce
1. Open a roll call
2. Scan several QR
3. Maybe see error (Not sure how to reproduce for now)

### Version & Environment
This bug was reproduced on:
- Commit: 4e0323d020fbcfb97612de1fa685a4cddb220ab2

##### Front-ends:
- [ ] Fe1-Web (please include browser's names & version)
- [x] Fe2-Android (please specify if phone or emulation, and Android version)
- [ ] Not applicable

##### Back-ends:
- [ ] Be1-Go
- [ ] Be2-Scala
- [x] Not applicable

### Impact
This would be a severe problem in production. Believing that the token count is wrong break the PoP principles

**Comment by GabrielFleischer** [comment]
A way to reproduce the issue is to open a Roll Call, leave it without closing it and open another Roll Call.

My guess is that this is due to the fact that the scanned attendees are not cleared when opening a Roll Call and that we can open a Roll Call while another is already opened.

**Comment by Warhedgehog** [comment]
Was fixed

**Comment by GabrielFleischer** [comment]
This has been fixed throughout the refactoring.
