### ISSUE TITLE
[BUG] Sending the same amount of money twice does not work

### ISSUE THREAD

**Issue by Tyratox** [dedis/popstellar#1259]
### Description (Actual behavior)
The coin(-base) transactions currently do not include a timestamp or nonce resulting in equal message ids for the same set of receivers and the same amount. Thus only the first is actually processed.

### How to reproduce
1. Send the same amount of coins to the same person twice

### Version & Environment
This bug was reproduced on:
- Commit: a0c8d16c74b8f64d4c710aa9b9acea2610bc4f8b

##### Front-ends:
- [x] Fe1-Web (please include browser's names & version)
- [x] Fe2-Android (please specify if phone or emulation, and Android version)
- [ ] Not applicable

##### Back-ends:
- [x] Be1-Go
- [x] Be2-Scala
- [ ] Not applicable

**Comment by lourkeur** [comment]
is this #1153?

Does this apply to non-coinbase transactions? If there are inputs, input hashes should serve as de-facto nonces.

**Comment by Tyratox** [comment]
Yes, closing since it's a duplicate
