### ISSUE TITLE
[BUG] The GreetLao message contains the wrong address

### ISSUE THREAD

**Issue by GabrielFleischer** [dedis/popstellar#1290]
### Description (Actual behavior)
The go backend sends this address with the GreetLao message :
`wss://localhost:15000/organizer/client`

### Expected behavior
The expected address would point to the same server as
`wss://popdemo.dedis.ch/go`

### How to reproduce
1. Connect to a Go backend
2. See the message in the logs

### Version & Environment
This bug was reproduced on:
- Commit: f31c5ad2a851ff28a644640e25d3f0c16a84bc5c

##### Front-ends:
- [ ] Fe1-Web (please include browser's names & version)
- [ ] Fe2-Android (please specify if phone or emulation, and Android version)
- [x] Not applicable

##### Back-ends:
- [x] Be1-Go
- [ ] Be2-Scala
- [ ] Not applicable

##### Environment (as applicable):
 - Device: Dedis's server
 - OS: Linux ?

### Workaround
None

### Impact
The feature is not used in the app currently, so it's not an issue

### Possible root cause
The address of the device is not configured correctly.

**Comment by MariemBaccari** [comment]
@GabrielFleischer in [this PR](https://github.com/dedis/popstellar/pull/1559) I added the option of entering the client and the server addresses directly in the config file before running the servers. That way, the greet lao will send the exact address you tell him the server has. Do you think that's enough for solving this issue ?

**Comment by GabrielFleischer** [comment]
> @GabrielFleischer in [this PR](https://github.com/dedis/popstellar/pull/1559) I added the option of entering the client and the server addresses directly in the config file before running the servers. That way, the greet lao will send the exact address you tell him the server has. Do you think that's enough for solving this issue ?

It seems to be a valid fix. Great job!
