### ISSUE TITLE
Replace three dots by trash can in socal media feature

### ISSUE THREAD

**Issue by Tyratox** [dedis/popstellar#1409]
Be sure to add a confirmation modal (there is a ConfirmModal component) to make sure chirps are not deleted accidentally.

<img width="562" alt="Screenshot 2023-02-22 at 12 32 44" src="https://user-images.githubusercontent.com/2634739/220608501-92d89eca-ca29-41fc-ad02-2adb888b9570.png">

<img width="562" alt="Screenshot 2023-02-22 at 12 32 45" src="https://user-images.githubusercontent.com/2634739/220608510-963a4076-d058-4446-bb2f-c6243a6e4aac.png">

**Comment by Yasir761** [comment]
I want to work on this but I didn't get what to add in replace of three dots icon.

**Comment by Tyratox** [comment]
I thought a trash can would for instance be more user friendly as currently the only action hidden behind the three dots is the chirp's deletion which means we can also just put that one action there instead of the three dots.

Most likely a confirmation modal is still desired to prevent accidental deletions of chirps.

Does this make sense?
