### ISSUE TITLE
Rejecting network messages that open a roll call when one is already open 

### ISSUE THREAD

**Issue by matteosz** [dedis/popstellar#1422]
### Description
Following the PR #1414, we fixed the opening of a new roll call when another one is opened at the user interaction level. However, on a specification level, this leads to a potential issue. Hence, missing a close Roll Call message would put the app in an undesired state from which no other Roll Call can be opened.

##### Front-ends:
- [X] Fe1-Web
- [X] Fe2-Android
- [ ] Not applicable

##### Back-ends:
- [ ] Be1-Go
- [ ] Be2-Scala
- [X] Not applicable

**Comment by pierluca** [comment]
@matteosz how do you propose to resolve this ? 
should back-ends also prevent this ?

**Comment by matteosz** [comment]
In the possibile future scenario where multiple organizers are possible (i.e. witness and organizer become the same entity), then I guess that there's no escape from the back-ends preventing this. This is due to the fact that at the same time all the users can open the roll call, and there's no way for the front-ends to prevent that, as locally they have no other opened roll call at that time.

Sticking with the current implementation (single organizer), then a resilient communication could prevent the possibility of losing such closing message. For instance, if the server which the client is connected to fails temporarly before sending back a close call, then there should be resilience nevertheless. So, implementing a protocol for multi-server connection and server-to-server gossiping should be a possible solution to that.
