### ISSUE TITLE
Question name in the election can be made of only spaces

### ISSUE THREAD

**Issue by matteosz** [dedis/popstellar#1428]
### Description (Actual behavior)
When creating a question, the check is only on the fact that the name is actually empty. However, it can be made of just space characters, resulting visually empty as well (i.e. the text is not trimmed).

![elec_screen](https://user-images.githubusercontent.com/83547952/222894979-85a0f70c-7099-4fd7-9a66-853cf6c628df.png)

### Expected behavior
The current implementation in FE2 doesn't allow the user to type a string of just spaces as the first question (otherwise it's not possible to create the election), while it gives the possibility to do so with next questions. However such questions are not considered valid during the election and, thus, not displayed.

![Screenshot (26)](https://user-images.githubusercontent.com/83547952/222895430-e23dd6c9-2890-49e0-809f-e3afddec41a3.png)
|:--:| 
| *First question of election with spaces* |

![Screenshot (27)](https://user-images.githubusercontent.com/83547952/222895494-130ce802-b593-4475-a0a8-0733438a4720.png)
|:--:| 
| *Second question with spaces after a valid first question* |

![Screenshot (28)](https://user-images.githubusercontent.com/83547952/222895521-0f2bb50f-2924-4a7d-8f9b-870938b34f10.png)
|:--:| 
| *Final election result with second question discarded* |

### How to reproduce
1. Go to 'Create Election'
2. Insert the name
3. Type in Question 1 box a space " "
4. Add random balot options
5. Click on Add question
6. Type in Question 2 box 2 spaces "  "
7. Add random balot options
8. Click confirm

### Version & Environment
This bug was reproduced on the current online version of the FE1 (https://fe1.personhood.online)

##### Front-ends:
- [X] Fe1-Web
- [ ] Fe2-Android
- [ ] Not applicable

##### Back-ends:
- [ ] Be1-Go
- [ ] Be2-Scala
- [X] Not applicable

### Impact
Not impacting in terms of functionality, but just in terms of usability and coherence.

**Comment by pierluca** [comment]
Nice catch ! 

Just to clarify, "this bug was reproduced on the current online version of the FE1 (https://fe1.personhood.online/) "
This was FE1-V1.3 | A332107 | 21/02/23 22:36

Also, @matteosz, are you saying that fe2 silently removes the question ?
If so, shouldn't it block the creation of the question in the first place, instead of silently removing it ?

**Comment by matteosz** [comment]
The main reason is that there's no delete button after a user press on 'Add question'. Therefore, if the user wanted to not insert anymore the question it could simply clear it out instead of restarting the election creation. Also, the fe2 interprets the string empty and the string with just spaces as equivalent since the content is trimmed.

> Nice catch !
> 
> Just to clarify, "this bug was reproduced on the current online version of the FE1 (https://fe1.personhood.online/) " This was FE1-V1.3 | A332107 | 21/02/23 22:36
> 
> Also, @matteosz, are you saying that fe2 silently removes the question ? If so, shouldn't it block the creation of the question in the first place, instead of silently removing it ?
