### ISSUE TITLE
[BUG] Error catchup for election results

### ISSUE THREAD

**Issue by matteosz** [dedis/popstellar#1472]
### Description (Actual behavior)
The catchup message related to a closed election isn't working. As a consequence, the client sees "Waiting for results" permanently even though the results have already been published. This happens in FE2 as there's no persistency so far, while FE1 stores in browser's cache the results, so persistency client side could fix the issue, but it's probably better to have a working catchup.

Error message on FE2: 

> E/LAONetworkManager: Error while handling received catchup message
>     com.github.dedis.popstellar.utility.error.UnknownElectionException: Election with id \<id\> is unknown.

### Expected behavior
The user should see the results of a closed election upon reconnection.

### How to reproduce
1. Create an election, open it, collect votes and then close it
2. Check that results are visible
3. Close the application so that connections are closed
4. Reopen the application and click on that election

### Version & Environment
This bug was reproduced on:
- Commit: 84f24960ac1162dbc682ca0f06ebce02b54a3fde

##### Front-ends:
- [ ] Fe1-Web
- [ ] Fe2-Android
- [X] Not applicable

##### Back-ends:
- [X] Be1-Go
- [x] Be2-Scala
- [ ] Not applicable

### Impact
Results of old elections become unavailable as one closes the application.

**Comment by K1li4nL** [comment]
I couldn't reproduce the bug on either of Master: 06860647510fbcd5370bd611a33878b62f857cd6

**Comment by MariemBaccari** [comment]
The issue still exists in go. I'm fixing it.
