### ISSUE TITLE
[BUG] Wallet seed lost on app inactivity

### ISSUE THREAD

**Issue by simone-kalbermatter** [dedis/popstellar#1489]
### Description (Actual behavior)
During the global meetings it was observed that on some phones the wallet seed was lost and the _Set up wallet_ screen was shown after turning the screen off and not using the phone for a while. However this was not reproducable on all phones.

### Expected behavior
The wallet seed should never be lost and the user not logged out unless _Wallet log out_ is clicked.

### How to reproduce
1. Set up the wallet seed
2. Join a Lao (possibly even without connecting to a lao)
3. Turn off screen and wait for a bit

### Version & Environment
This bug was reproduced on:
- Commit: c0c0af4 (release all-v1.7)

##### Front-ends:
- [ ] Fe1-Web
- [x] Fe2-Android
- [ ] Not applicable

##### Back-ends:
- [ ] Be1-Go
- [ ] Be2-Scala
- [x] Not applicable (not sure anymore which back-end was used but it should be a front-end problem)

##### Environment (as applicable):
 - Device: Pierluca's and Kilian's phone 😄 (Could NOT be reproduced on Nokia X20 using Android 13)
 - OS:  Android 12, Android 13

### Impact
The user loses their wallet seed forever, which makes the app unusable.

### Possible root cause
There is some error with handling the persistence of the keys. Possibly it is also related to the phone's settings.

**Comment by matteosz** [comment]
This should have been fixed through persistency, as it was probably due to a problem of ram being cleared.
