### ISSUE TITLE
Connect to local mock server button should be hidden for release

### ISSUE THREAD

**Issue by simone-kalbermatter** [dedis/popstellar#1590]
The button _Connect to LocalMockServer_ on the launch new lao screen should be hidden for the release.

**Comment by simone-kalbermatter** [comment]
The button _Connect to LocalMockServer_ on the launch new lao screen should be hidden for the release.

**Comment by MariemBaccari** [comment]
Solved in https://github.com/dedis/popstellar/pull/1618
