### ISSUE TITLE
Option to create a meeting should be hidden for release

### ISSUE THREAD

**Issue by simone-kalbermatter** [dedis/popstellar#1591]
When chosing to create a new event, the _Create Meeting_ option should be hidden for the release.

**Comment by simone-kalbermatter** [comment]
When chosing to create a new event, the _Create Meeting_ option should be hidden for the release.

**Comment by MeKHell** [comment]
Is there a reason why meetings should be hidden ? Aren't they stable and supported by both backends ? @simone-kalbermatter

**Comment by simone-kalbermatter** [comment]
@MeKHell Offically, Meetings are not part of the features we are releasing and there are no tests for it, so I think it's better to remove it (unless it's a big effort, because this is not really important).
