### ISSUE TITLE
[BUG] Release version number overlaps side menu

### ISSUE THREAD

**Issue by simone-kalbermatter** [dedis/popstellar#1592]
<img src="https://github.com/dedis/popstellar/assets/71314469/d0dc775f-d471-4e86-8b72-4c5cef146882.png" 
     width="250" />

This happens on mobile and on desktop if the window is too small.

**Comment by MeKHell** [comment]
Increasing the priority, since it might take too much space on mobile and shadows more than the half of the top left button (burger menu or go back).
