### ISSUE TITLE
[BUG] Long line break in chirp accepted

### ISSUE THREAD

**Issue by dayan9265** [dedis/popstellar#1627]
### Description (Actual behavior)
Users can send chirps with 300 line breaks, which when displayed make it seems like there's a visual bug

![image](https://github.com/dedis/popstellar/assets/82887324/d7e27a4f-4490-48b9-803f-ece1dfc74277)

### Expected behavior
Long line break should be trimmed

### How to reproduce
1. Go to Social media
2. Send messages with lots of line breaks
3. Look at the message displayed

### Version & Environment
This bug was reproduced on:
- Commit: 71152f31d54630416f52d55b68ea3aea5575ebe5 (release branch)

##### Front-ends:
- [x] Fe1-Web (Firefox 113.0.2)
- [ ] Fe2-Android (haven't tested the behavior)
- [ ] Not applicable

##### Back-ends:
- [x] Be1-Go
- [x] Be2-Scala
- [ ] Not applicable
-> Back-ends need to agree on which format of chirps are accepted

##### Environment (as applicable):
 - OS: [Windows 11]
 - Browser: [Firefox 113.0.2]

### Workaround
Scroll on the page to look for the other chirps

### Impact
Screen looks weird, and also it takes time for the user to see the other chirps

### Possible root cause
No trimming of the messages

**Comment by MeKHell** [comment]
I think that the easiest fix regarding time left would be to completely remove line breaks and trim the chirp content. If the user needs to publish multiple paragraphs, he can still send several messages since we do not have a spam limiter.
