### ISSUE TITLE
Attendees can create an Lao and an election

### ISSUE THREAD

**Issue by flmichel** [dedis/popstellar#357]
It is now possible to create a Lao and an election with any public key so any attendee can create lao/elections. This shouldn't be the case. Only the organizer client should such events for now.

**Comment by rjaccard** [comment]
I have started to work on this issue.

**Comment by rjaccard** [comment]
I have submitted a PR for this issue (https://github.com/dedis/student_21_pop/pull/650). I will close it when it is merged.
