### ISSUE TITLE
[BUG] <title> is not set

### ISSUE THREAD

**Issue by ineiti** [dedis/popstellar#557]
### Description (Actual behavior)

When visiting https://popdemo.dedis.ch/, the title of the tab shows `undefined`

### Expected behavior

Show something like `PoPdemo` or so.

### How to reproduce

1. Visit https://popdemo.dedis.org
2. Look at tab

### Version & Environment
This bug was reproduced on:
- Deployed frontend

##### Front-ends:
- [x] Fe1-Web (Chrome)
- [ ] Fe2-Android (please specify if phone or emulation, and Android version)
- [ ] Not applicable

##### Back-ends:
- [ ] Be1-Go
- [ ] Be2-Scala
- [ ] Not applicable

### Impact
Slight annoyance

### Possible root cause
Find where to change the title of the page

**Comment by Tyratox** [comment]
Not the case anymore :)
