### ISSUE TITLE
Cannot (re)connect to LAO

### ISSUE THREAD

**Issue by celinecamacho** [dedis/popstellar#579]
### Description (Actual behavior)
When connected to a LAO, closing and reopening the window brings you back to the home page and not the LAO page. Trying to connect to the same LAO from the same device after that is not possible.

### Expected behavior
Either find the LAO page or have the possibility to reconnect to the LAO.

### How to reproduce
1. Open popdemo.dedis.ch
1. Connect to LAO
2. Close window
3. Open demo.dedis.ch in a new (incognito or not) window 
4. Try to connect to the same LAO

##### Front-ends:
- Fe1-Web 

##### Back-ends:
- Be2-Scala

##### Environment (as applicable):
 - OS: iOS 14
 - Browser: Safari 14.8.1, Chrome 95

### Workaround
Not closing the window after connecting to a LAO.

### Impact
If the user closes the window it looses all the information from the connection (LAO, events, etc.).

### Possible root cause
- The backend does not accept the same user to subscribe twice to a LAO. 
- The frontend does not save the state of the application

### Logs
```
17:06:44.616 [pop-be2-inner-actor-system-akka.actor.default-dispatcher-13] INFO  ch.epfl.pop.pubsub.ClientActor - Sending an answer back to client Some(Actor[akka://pop-be2-inner-actor-system/system/Materializers/StreamSupervisor-0/$$+-actorRefSource#-799747413]): ClientAnswer(Left(JsonRpcResponse(2.0,None,Some(ErrorObject(-1,Could not subscribe client to channel '/root/b0gXkHOJ43DSpuxMiXzWOCvUb-khqHqkxIbbKJVsiKM=': Actor Actor[akka://pop-be2-inner-actor-system/user/$u#-2005753943] was already subscribed to channel '/root/b0gXkHOJ43DSpuxMiXzWOCvUb-khqHqkxIbbKJVsiKM=')),Some(3))))
```

**Comment by pierluca** [comment]
This has been fixed as part of the code clean-up 😄
