### ISSUE TITLE
Adding an OpenElection message to the protocol

### ISSUE THREAD

**Issue by arnauds5** [dedis/popstellar#651]
Currently the start of an election is only based on the start time from the setup.
Organizer/witnesses can aggree to start it using a consensus, but they need to inform others that it was accepted.
One way of doing that is by adding an OpenElection message and by allowing vote only after it was opened (and before it was ended).

An election will have the following phases:
Setup → **Open** → Cast vote(s) → End → Result

An OpenElection data will be something like this (and will be publish in the election channel) : 
```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/dedis/student_21_pop/master/protocol/query/method/message/data/dataOpenElection.json",
    "description": "Match an OpenElection query",
    "type": "object",
    "properties": {
        "object": {
            "const": "election"
        },
        "action": {
            "const": "open"
        },
        "lao": {
            "type": "string",
            "contentEncoding": "base64",
            "$comment": "ID of the LAO"
        },
        "election": {
            "type": "string",
            "contentEncoding": "base64",
            "$comment": "ID of the election"
        },
        "opened_at": {
            "description": "[Timestamp] start time",
            "type": "integer",
            "minimum": 0
        }
    },
    "additionalProperties": false,
    "required": [
        "object",
        "action",
        "lao",
        "election",
        "opened_at"
    ]
}
```

The modifications will need to be implemented in both backend/frontend.

This is up to discussion, what do you think ?

**Comment by rjaccard** [comment]
This is a good idea! Very coherent with the current protocol and this fits the consensus very well. It might be a bit late in the semester to implement this change on the 4 systems but worths investigating the next semester I believe.

**Comment by Tesa27** [comment]
All the sub-systems now support open election and the protocol specification changed to reflect this, since it all the work has been merged to master we can close this issue
