### ISSUE TITLE
TextInput gets unselected as soon as we select it

### ISSUE THREAD

**Issue by Xelowak** [dedis/popstellar#716]
### Description (Actual behavior)
When you click on a text input in the web frontend (fe1), it often unselects the text input directly, and you have to click on it again to be able to write.

### Expected behavior
The text input remains selected when you click on it.

### How to reproduce
1. Open the web-frontend
2. Click on a text input somewhere (for example for launching an LAO)
3. See what happens

### Version & Environment
This bug was reproduced on:
- Commit: db5d109 (can be reproduced on master, as nothing has been done for it)

##### Front-ends:
- [x] Fe1-Web
- [ ] Fe2-Android 
- [ ] Not applicable

##### Back-ends:
- [ ] Be1-Go
- [ ] Be2-Scala
- [x] Not applicable

##### Environment (as applicable):
 - Device: Mac
 - OS: macOS Monterey 12.0.1
 - Chrome 96.0.4664.110

### Workaround
Click on the text input to select it again.

### Impact
No real impact, it is just annoying.

### Possible root cause
It might be an issue with React text inputs.

**Comment by Tyratox** [comment]
Was resolved by some PR in the last year
