### ISSUE TITLE
[BUG] Go CI is erroring

### ISSUE THREAD

**Issue by lourkeur** [dedis/popstellar#928]
### Description (Actual behavior)
The Go CI cannot find the `staticcheck` binary

### Expected behavior
The Go CI should do useful things

### How to reproduce
https://github.com/dedis/popstellar/runs/5832944411?check_suite_focus=true#step:7:508

### Version & Environment
This bug was reproduced on:
- GitHub actions

##### Front-ends:
- [ ] Fe1-Web (please include browser's names & version)
- [ ] Fe2-Android (please specify if phone or emulation, and Android version)
- [x] Not applicable

##### Back-ends:
- [x] Be1-Go
- [ ] Be2-Scala
- [ ] Not applicable

##### Environment (as applicable):
N/A

### Workaround
Don't know

### Impact
CI is less useful

### Possible root cause
Looks like the failure comes from outside of our control. Maybe the Docker image. I'm not sure though

**Comment by lourkeur** [comment]
It looks like @Warhedgehog is on it

**Comment by Warhedgehog** [comment]
True

**Comment by Warhedgehog** [comment]
This should be fixed definitely by #974
