### ISSUE TITLE
[BUG] message_id never verified on scala backend

### ISSUE THREAD

**Issue by Tesa27** [dedis/popstellar#939]
### MessageId is not checked on Scala backend

The message is simply stored with messageId as key, but when sending some messageId that does not represent the hash(data||signature) the backend does not send an error message and as such the integrity check fails.

**Comment by lourkeur** [comment]
Cannot reproduce:
I took `protocol/examples/query/publish/publish.json`. I tried corrupting either `message.data` or `messageId` I get `{"jsonrpc":"2.0","id":4,"error":{"code":-4,"description":"MessageValidator content validation failed: Invalid message_id"}}`

**Comment by Tesa27** [comment]
I was unable to reproduce the error too, it was maybe some other bug that caused this one. You reproduced the error running Karate or did you use some other method?

**Comment by lourkeur** [comment]
I pasted the request into Hoppscotch.

**Comment by Tesa27** [comment]
I am closing this issue since it was not a direct bug, but caused by another bug that was fixed, if the bug reappears we will reopen this issue
