### ISSUE TITLE
[BUG] Signature is not checked well on backends

### ISSUE THREAD

**Issue by Tesa27** [dedis/popstellar#940]
##### Back-ends:
- [x] Be1-Go
- [ ] Be2-Scala
- [ ] Not applicable

**Comment by Tesa27** [comment]
Signature is not checked on go backend, and partially checked on Scala backend

**Comment by lourkeur** [comment]
Could you provide a testcase or some details for the "partially checked" issue on the Scala back-end?

**Comment by lourkeur** [comment]
Now fixed
